debug : 1
xpath_conf : conf/xpath.yml
event_id_cache : conf/eventId-cache.yml
soap_global_uri : https://api.betfair.com/global/v3/BFGlobalService
soap_exchange_uri : https://api.betfair.com/exchange/v3/BFExchangeService
soap_response_templates : tmpl/soap-responses/
cycle : 60
error : 
THROTTLE_EXCEEDED : "slow down"
