# turn on tracing output
debug : 1

# useful xpaths
xpath_conf : conf/xpath.yml

# a cached list of top-level event id's, eg. Soccer = 1
event_id_cache : conf/eventId-cache.yml

# end points for SOAP requests
soap_global_uri : https://api.betfair.com/global/v3/BFGlobalService
soap_exchange_uri : https://api.betfair.com/exchange/v5/BFExchangeService

# soap request templates (HTML::Template)
soap_response_templates : tmpl/soap-responses/

# seconds to wait in between reseting throttle requests
cycle : 60

# directory to write log files to. leave blank if you do not want various processes to write logs.
log : 

# each time a request is made we can cache the session key returned. this allows multiple applications
# to bypass the login and use the same session
session : log/session
